/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DocumentTypeMarker: typeof import('./src/components/DocumentTypeMarker.vue')['default']
    FormatFromJsonDemo: typeof import('./src/components/FormatFromJsonDemo.vue')['default']
    Formatter: typeof import('./src/components/Formatter.vue')['default']
    FormatterInput: typeof import('./src/components/FormatterInput.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NUpload: typeof import('naive-ui')['NUpload']
    PublicationSection: typeof import('./src/components/PublicationSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleSection: typeof import('./src/components/TitleSection.vue')['default']
  }
}
